# Generated by Django 3.0.7 on 2020-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='room_cover'),
        ),
    ]
