# Generated by Django 3.0.7 on 2020-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_room_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
