# Generated by Django 3.0.7 on 2020-09-10 14:16

from django.db import migrations, models
import hotel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_room_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=hotel_app.models.room_images_upload_path),
        ),
    ]
