# Generated by Django 3.0.7 on 2020-09-10 14:29

from django.db import migrations, models
import hotel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_auto_20200910_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='display_images',
            field=models.FileField(null=True, upload_to=hotel_app.models.room_images_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(upload_to=hotel_app.models.room_images_upload_path),
        ),
    ]
