# Generated by Django 3.0.7 on 2020-09-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_auto_20200910_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='display_images',
        ),
    ]
