# Generated by Django 3.0.7 on 2020-09-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_auto_20200912_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_out_date',
            new_name='checkout_date',
        ),
    ]
